language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t asciineo/react-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run asciineo/react-test npm test -- --coverage
  - docker run -e CI=true asciineo/react-test npm test

after_success:
  - docker build -t asciineo/multi-client ./client
  - docker build -t asciineo/multi-nginx ./nginx
  - docker build -t asciineo/multi-server ./server
  - docker build -t asciineo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push asciineo/multi-client
  - docker push asciineo/multi-nginx
  - docker push asciineo/multi-server
  - docker push asciineo/multi-worker
